- name: Upload build logs on failure
  if: failure()
  uses: actions/upload-artifact@v4.3.3  # Pinned to exact stable version
  with:
    name: build-logs
    path: |
      ${{ github.workspace }}/docker.log
      ${{ github.workspace }}/build.log
    retention-days: 3  # Optional: keeps logs for 3 days